// Generated by scripts/generate-mastery-kits.mjs. Do not edit by hand.
// Uses only Node.js built-ins and never reads a reference solution directory.

import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const candidateRoot = existsSync(join(projectRoot, "starter"))
  ? join(projectRoot, "starter")
  : projectRoot;
const read = (path) => readFileSync(join(candidateRoot, path), "utf8");

const css = read("styles.css");
const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "");
const rule = (selector) => {
  const escaped = selector.replace(/[.*+?^\${}()|[\]\\]/g, "\\$&");
  return withoutComments.match(new RegExp(escaped + "\\s*{([^}]*)}", "i"))?.[1] ?? "";
};

test("uses border-box and reveals the skip link on focus", () => {
  assert.match(withoutComments, /\*\s*,\s*\*::before\s*,\s*\*::after\s*{[^}]*box-sizing\s*:\s*border-box/si);
  assert.match(rule(".skip-link"), /\bposition\s*:\s*absolute/i);
  assert.match(rule(".skip-link:focus"), /\b(?:inset|inset-inline-start|left)\s*:/i);
});

test("creates a wrapping semantic navigation with usable states", () => {
  const list = rule(".nav-list");
  assert.match(list, /\bdisplay\s*:\s*flex/i);
  assert.match(list, /\bflex-wrap\s*:\s*wrap/i);
  assert.match(list, /\blist-style\s*:\s*none/i);
  assert.match(list, /\bpadding\s*:\s*0/i);
  assert.match(rule(".nav-list a"), /\bmin-height\s*:/i);
  assert.ok(/\.nav-list a:hover\s*{[^}]+}/si.test(withoutComments));
  assert.match(withoutComments, /:focus-visible\s*{[^}]*outline\s*:\s*(?!none)/si);
  assert.match(withoutComments, /\[aria-current=["']?page["']?\]\s*{[^}]*(?:font-weight|text-decoration)/si);
});

test("starts stacked and changes to a row at a content breakpoint", () => {
  assert.match(rule(".site-header"), /\bdisplay\s*:\s*flex/i);
  assert.match(rule(".site-header"), /\bflex-direction\s*:\s*column/i);
  assert.match(withoutComments, /@media\s*\([^)]*min-width[^)]*\)\s*{[\s\S]*?\.site-header\s*{[^}]*flex-direction\s*:\s*row/si);
});
